
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class VelocityDialog extends javax.swing.JDialog {

    public boolean IsOK() {
        return isOK;
    }

    public VelocityDialog() {

    }

    public Measurement getMeasurement() {
        return m;
    }
    boolean isOK = true;
    Measurement m = null;

    /**
     * Creates new form AppointmentDialog
     */
    public VelocityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfKennzeichen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGemessen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfErlaubt = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Termin-Eingabe");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("             Datum:");
        getContentPane().add(jLabel2);

        tfDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDate.setText("29.03.2002");
        tfDate.setBorder(null);
        getContentPane().add(tfDate);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("            Uhrzeit:");
        getContentPane().add(jLabel3);

        tfTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTime.setText("12:30");
        tfTime.setBorder(null);
        tfTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimeActionPerformed(evt);
            }
        });
        getContentPane().add(tfTime);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("         Kennzeichen:");
        getContentPane().add(jLabel4);

        tfKennzeichen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKennzeichen.setText("GU-RASER1");
        tfKennzeichen.setBorder(null);
        getContentPane().add(tfKennzeichen);

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("           V-Gemessen:");
        getContentPane().add(jLabel5);

        tfGemessen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfGemessen.setText("120");
        tfGemessen.setBorder(null);
        getContentPane().add(tfGemessen);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("             V-Erlaubt:");
        getContentPane().add(jLabel6);

        tfErlaubt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfErlaubt.setText("100");
        tfErlaubt.setBorder(null);
        getContentPane().add(tfErlaubt);

        btAdd.setText("Übernehmen");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd);

        btCancel.setText("Abbrechen");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            LocalDateTime datum = LocalDateTime.parse(tfDate.getText() + " " + tfTime.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"));
            String kz = tfKennzeichen.getText();
            int vErlaubt = Integer.parseInt(tfErlaubt.getText());
            double vGemessen = Double.parseDouble(tfGemessen.getText());
            this.dispose();
            m = new Measurement(datum, kz, vErlaubt, vGemessen);
            isOK = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falsche Eingabe.");
        }
        
    }//GEN-LAST:event_btAddActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
        isOK = false;
    }//GEN-LAST:event_btCancelActionPerformed

    private void tfTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDialog dialog = new VelocityDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfErlaubt;
    private javax.swing.JTextField tfGemessen;
    private javax.swing.JTextField tfKennzeichen;
    private javax.swing.JTextField tfTime;
    // End of variables declaration//GEN-END:variables
}
